"""
Pull request generator for submitting contributions.
"""

import os
from dataclasses import dataclass
from typing import Any

import structlog

logger = structlog.get_logger()


@dataclass
class PRDetails:
    """Details for a pull request."""

    title: str
    body: str
    branch: str
    base: str = "main"
    draft: bool = False
    labels: list[str] | None = None

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary."""
        return {
            "title": self.title,
            "body": self.body,
            "branch": self.branch,
            "base": self.base,
            "draft": self.draft,
            "labels": self.labels or [],
        }


class PRGenerator:
    """
    Generates well-formatted pull requests.

    Creates PR titles and bodies that follow best practices
    and include relevant context.
    """

    # PR body template
    PR_TEMPLATE = """## Summary

{summary}

## Related Issue

Fixes #{issue_number}

## Changes Made

{changes}

## Testing

{testing}

## Checklist

- [x] Code follows project style guidelines
- [x] Tests pass locally
- [x] Documentation updated (if applicable)
- [ ] Ready for review

---

*This PR was generated by [git-gud-samaritans](https://github.com/williamzujkowski/git-gud-samaritans) 🎮*
"""

    def __init__(self, github_token: str | None = None):
        """
        Initialize the PR generator.

        Args:
            github_token: GitHub personal access token
        """
        self.github_token = github_token or os.getenv("GITHUB_TOKEN")

    def generate(
        self,
        issue_url: str,
        issue_title: str,
        issue_body: str,
        changes: list[str],
        branch_name: str,
        testing_notes: str | None = None,
    ) -> PRDetails:
        """
        Generate PR details from issue and changes.

        Args:
            issue_url: URL to the issue being fixed
            issue_title: Title of the issue
            issue_body: Body of the issue
            changes: List of changes made
            branch_name: Name of the branch with changes
            testing_notes: Optional testing notes

        Returns:
            PRDetails with generated content
        """
        logger.info("generating_pr", issue_url=issue_url, branch_name=branch_name)

        # Parse issue number from URL
        issue_number = int(issue_url.split("/")[-1])

        # Generate title
        title = self._generate_title(issue_title)

        # Generate body
        body = self._generate_body(
            issue_number=issue_number,
            issue_body=issue_body,
            changes=changes,
            testing_notes=testing_notes,
        )

        return PRDetails(
            title=title, body=body, branch=branch_name, labels=["git-gud-samaritans"]
        )

    def _generate_title(self, issue_title: str) -> str:
        """Generate a PR title from the issue title."""
        # Clean up issue title
        title = issue_title.strip()

        # Remove common prefixes
        prefixes_to_remove = ["[Bug]", "[Feature]", "[Enhancement]", "Bug:", "Feature:"]
        for prefix in prefixes_to_remove:
            if title.lower().startswith(prefix.lower()):
                title = title[len(prefix) :].strip()

        # Ensure it starts with a verb
        if not any(
            title.lower().startswith(v)
            for v in ["fix", "add", "update", "remove", "improve"]
        ):
            # Try to infer the action
            if (
                "bug" in title.lower()
                or "error" in title.lower()
                or "issue" in title.lower()
            ):
                title = f"Fix: {title}"
            elif "add" in title.lower() or "new" in title.lower():
                title = f"Add: {title}"
            else:
                title = f"Update: {title}"

        return title

    def _generate_body(
        self,
        issue_number: int,
        issue_body: str,
        changes: list[str],
        testing_notes: str | None,
    ) -> str:
        """Generate a PR body."""
        # Generate summary from issue
        summary = self._summarize_issue(issue_body)

        # Format changes
        if changes:
            changes_text = "\n".join(f"- {change}" for change in changes)
        else:
            changes_text = "- See commit history for details"

        # Format testing notes
        if testing_notes:
            testing_text = testing_notes
        else:
            testing_text = (
                "- Ran existing test suite\n- Verified changes work as expected"
            )

        return self.PR_TEMPLATE.format(
            summary=summary,
            issue_number=issue_number,
            changes=changes_text,
            testing=testing_text,
        )

    def _summarize_issue(self, issue_body: str, max_length: int = 500) -> str:
        """Summarize the issue body for the PR."""
        if not issue_body:
            return "Addresses the linked issue."

        # Take first paragraph or truncate
        summary = issue_body.split("\n\n")[0]

        if len(summary) > max_length:
            summary = summary[: max_length - 3] + "..."

        return summary

    def submit(self, repo: str, pr_details: PRDetails) -> str:
        """
        Submit a pull request to GitHub.

        Args:
            repo: Repository full name (owner/repo)
            pr_details: PR details to submit

        Returns:
            URL of the created PR
        """
        logger.info(
            "submitting_pr", repo=repo, branch=pr_details.branch, title=pr_details.title
        )

        # TODO: Implement actual PR submission using GitHub API
        # For now, return a placeholder

        return f"https://github.com/{repo}/pull/NEW"
